debug = true

address = "0.0.0.0:19090"

[db]
address = "127.0.0.1"
port = 33306
user = "root"
password = "Zuo@20250306"
db_name = "qa"
max_open_conns = 10
max_idle_conns = 10

[milvus]
address = "127.0.0.1"
port = 19530

[llm]
base_url = "http://localhost:11434/v1"
api_key = "Empty"
model = "qwen2.5:7b"
temperature = 0.7
max_tokens = 2048
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0

[embedding]
base_url = "http://localhost:11434/v1"
api_key = "Empty"
model = "mxbai-embed-large"
